"""Replay Algorithm 3 certificates and group arithmetic without backtracking.

Witnesses, subgroup chains, canonical generator choices within the returned
group, and agreement with the separate modern groups are checked again.
Recorded final exhausted searches are not re-executed by this verifier.
"""
import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import sys
import time

import sage.all
from sage.env import SAGE_VERSION

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'lib'))
from historical_stabilizer import (permutation_group, generator_orbits, orbit_filter,
                                   printed_note9_filter)
from ea_equivalence import verify_ea_witness


def require(condition, message):
    if not condition:
        raise RuntimeError(message)


def elements(group, q):
    return {tuple(int(g(x + 1)) - 1 for x in range(q)) for g in group}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--record',type=Path,default=ROOT/'results/historical-stabilizers.json')
    parser.add_argument('--output',type=Path,default=ROOT/'build/historical-stabilizers-verification.json')
    args = parser.parse_args()
    start = time.perf_counter()
    record = json.loads(args.record.read_text())
    require(record['completed'], 'incomplete search record')
    for name in ('data/dimension-four.json','data/dimension-five.json'):
        require(hashlib.sha256((ROOT/name).read_bytes()).hexdigest() == record['source_sha256'][name],
                'published inputs differ from recorded inputs')
    targets = {
        4: json.loads((ROOT/'data/dimension-four.json').read_text())['ea_representatives'],
        5: [r['table'] for r in json.loads((ROOT/'data/dimension-five.json').read_text())['representatives']]}
    modern_path = ROOT/'results/ccz-stabilizers.json'
    require(hashlib.sha256(modern_path.read_bytes()).hexdigest() == record['modern_record_sha256'],
            'modern comparison record differs')
    modern = {d['dimension']:d for d in json.loads(modern_path.read_text())['dimensions']}
    keys = [(c['dimension'],c['representative']) for c in record['cases']]
    dimensions = sorted({n for n,_ in keys})
    require(keys == [(n,i) for n in dimensions for i in range(1,len(targets[n])+1)],
            'missing, duplicated, or reordered cases')
    checked = []
    totals = {n:0 for n in dimensions}
    witnesses = 0
    for case in record['cases']:
        n,index = case['dimension'],case['representative']
        q = 1 << n
        table = targets[n][index-1]
        gens = []
        group = permutation_group(gens,q)
        known_groups = []
        steps = case['steps']
        require(steps and steps[-1]['exhausted'] and
                not any(s['exhausted'] for s in steps[:-1]), 'invalid termination record')
        for step in steps:
            require(step['subgroup_order'] == int(group.order()), 'subgroup order differs')
            require(step['orbits'] == [list(o) for o in generator_orbits(gens,q)],
                    'recorded orbit is not generated by the selected permutations')
            if step['exhausted']:
                require('alpha' not in step, 'exhausted step contains a generator')
                continue
            witness = (step['alpha'],step['beta'],step['gamma'])
            verify_ea_witness(table,table,witness)
            witnesses += 1
            known_groups.append(elements(group,q))
            gens.append(tuple(step['alpha']))
            group = permutation_group(gens,q)
            require(step['next_subgroup_order'] == int(group.order()) > step['subgroup_order'],
                    'subgroup does not grow as recorded')
        full = elements(group,q)
        for alpha, known in zip(gens,known_groups):
            require(alpha == min(full-known), 'generator is not the least missing element')
        require(case['order'] == int(group.order()), 'final group order differs')
        reference = modern[n]['stabilizers'][index-1]
        other = []
        for w in reference['ea_generators']:
            verify_ea_witness(table,table,(w['alpha'],w['beta'],w['gamma']))
            other.append(w['alpha'])
        require(group == permutation_group(other,q), 'independent groups differ')
        linear_order = 1
        for i in range(n):
            linear_order *= q-(1 << i)
        action_order = q * linear_order * linear_order * q**(n+1)
        require(action_order % case['order'] == 0, 'orbit size is not integral')
        orbit_size = action_order // case['order']
        totals[n] += orbit_size
        checked.append(dict(dimension=n,representative=index,stabilizer_order=case['order'],
                            generators=len(gens),ea_group_order=action_order,ea_orbit_size=orbit_size))
    for n,total in totals.items():
        require(total == modern[n]['published_apn_total'], 'orbit total differs')
    note9_checks = None
    if record['note9']:
        from random import Random
        from affine_refinement import refine
        import runpy
        published = runpy.run_path(str(ROOT/'sage/historical_stabilizers.sage'))['note9_generators']()
        first = next(c for c in record['cases'] if (c['dimension'],c['representative']) == (5,1))
        require([tuple(s['alpha']) for s in first['steps'][:-1]] == published,
                'discovered generators do not equal the printed Note 9 permutations')
        orbits = generator_orbits(published,32)
        rng = Random(2008)
        accepted = rejected = 0
        # Fix the first two values so the five-position rule is exercised,
        # rather than almost every random trial failing immediately at 0.
        for _ in range(256):
            alpha = refine((None,)*32,0,0,injective=True)
            alpha = refine(alpha,1,1,injective=True)
            while None in alpha:
                x = alpha.index(None)
                alpha = refine(alpha,x,rng.choice([v for v in range(32) if v not in alpha]),
                               injective=True)
                actual = orbit_filter(alpha,orbits)
                require(actual == printed_note9_filter(alpha), 'Note 9 filters disagree')
                accepted += int(actual)
                rejected += int(not actual)
        require(accepted > 0 and rejected > 0, 'five-position rule was not exercised')
        note9_checks = dict(seed=2008,affine_prefixes=accepted+rejected,
                            accepted=accepted,rejected=rejected,
                            first_two_images_fixed=True,printed_generators_verified=True)
        positive = record['note9']['positive']
        verify_ea_witness(positive['source_table'],positive['target_table'],
                          (positive['alpha'],positive['beta'],positive['gamma']))
        witnesses += 1
        require(record['note9']['negative']['exhausted'] and
                not record['note9']['negative']['equivalent'], 'missing Note 9 negative test')
    names = ['sage/verify_historical_stabilizers.sage','sage/historical_stabilizers.sage',
             'lib/historical_stabilizer.py',
             'lib/affine_refinement.py','lib/apn_reference.py','lib/ea_equivalence.py']
    result = dict(artifact='historical-stabilizer-certificate-replay',completed=True,
                  finished_utc=datetime.now(timezone.utc).isoformat(),sage_version=SAGE_VERSION,
                  record_sha256=hashlib.sha256(args.record.read_bytes()).hexdigest(),
                  source_sha256={p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in names},
                  verified_witnesses=witnesses,cases=checked,ea_orbits_total=totals,
                  note9_checks=note9_checks,
                  negative_searches_reexecuted=False,
                  coverage='Orbit totals count all APN functions when combined with the separate completed EA classifications.',
                  seconds=time.perf_counter()-start)
    args.output.parent.mkdir(parents=True,exist_ok=True)
    args.output.write_text(json.dumps(result,indent=2,sort_keys=True)+'\n')
    print('{} witnesses replayed; subgroup chains and orbit totals verified'.format(witnesses))


if __name__ == '__main__':
    main()
